language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bryanjuela/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bryanjuela/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucker_path: "docker-react"
  on:
    branch: master